import { Link } from 'react-router-dom'
import { MessageCircle, Search, UserRound } from 'lucide-react'
import Avatar from '../ui/Avatar.jsx'
import PresenceIndicator from '../ui/PresenceIndicator.jsx'
import { useSocket } from '../../context/SocketContext.jsx'
import { formatRelativeTime } from '../../utils/formatters.js'

export default function ContextRail({ conversations = [] }) {
  const { onlineUsers } = useSocket()
  return <aside className="context-rail hidden min-h-screen w-[300px] shrink-0 px-5 py-8 min-[1180px]:block"><Link to="/explore" className="flex min-h-11 items-center gap-2 rounded-control border border-white/10 bg-white/5 px-3 text-sm text-white/55 transition hover:border-white/20 hover:text-white"><Search size={16} /> Search people</Link><div className="mt-10 space-y-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white/85">Recent conversations</h2><Link className="text-xs text-[var(--dh-primary-soft)] hover:underline" to="/messages">View all</Link></div>{conversations.length ? <div className="space-y-1">{conversations.slice(0, 4).map((conversation) => <Link key={conversation.id} to={`/messages/${conversation.participant.id}`} className="flex items-center gap-3 rounded-control px-2 py-2.5 text-white/70 transition hover:bg-white/5"><Avatar user={conversation.participant} size="sm" showPresence isOnline={onlineUsers.has(conversation.participant.id)} /><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="truncate text-sm font-medium text-white/90">{conversation.participant.fullName}</span><span className="meta text-white/35">{conversation.lastMessage?.createdAt ? formatRelativeTime(conversation.lastMessage.createdAt) : ''}</span></span><span className="block truncate text-xs text-white/45">{conversation.lastMessage?.text || 'Start a conversation'}</span></span></Link>)}</div> : <div className="space-y-3 rounded-card border border-white/10 p-4 text-center"><MessageCircle className="mx-auto h-6 w-6 text-white/35" /><p className="text-sm text-white/50">No messages yet.</p></div>}</div><div className="mt-10 space-y-4"><h2 className="text-sm font-semibold text-white/85">A quieter corner</h2><div className="rounded-card border border-white/10 p-4"><UserRound className="mb-3 h-5 w-5 text-[var(--dh-primary-soft)]" /><p className="text-sm leading-6 text-white/55">Find someone new to follow, then share something worth keeping.</p></div><PresenceIndicator isOnline={true} /></div></aside>
}
